export let restricted = [
	// paywall
	'The Wall Street Journal',
	'The New York Times',
	'The Washington Post',
	'Financial Times',
	'CNN',
	'Ground News',
	'Bloomberg',
	'Daily Wire',
	'Le Monde',
	// scrapping issues
	'Reuters',
	'POLITICO',
	'The Hill',
	'Axios',
	'Fortune',
]

export const defaultAgencyLevel = 1

export const agencyLevels = {
	// Level guide: 5 = top-tier wires/majors, 4 = major national/international, 3 = solid mainstream, 2 = niche/local.
	'associated press': 5,
	'ap news': 5,
	'reuters': 5,
	'bloomberg': 5,
	'financial times': 5,
	'the wall street journal': 5,
	'wsj': 5,

	'the new york times': 4,
	'new york times': 4,
	'the washington post': 4,
	'washington post': 4,
	'bbc': 4,
	'bbc news': 4,
	'the guardian': 4,
	'al jazeera': 4,
	'npr': 4,
	'pbs newshour': 4,
	'cnn': 4,
	'fox news': 4,
	'cnbc': 4,
	'politico': 4,
	'axios': 4,

	'usa today': 3,
	'abc news': 3,
	'cbs news': 3,
	'nbc news': 3,
	'time': 3,
	'newsweek': 3,
	'fortune': 3,
	'the hill': 3,
	'marketwatch': 3,
	'barron\'s': 3,
	'propublica': 3,
	'los angeles times': 3,
	'chicago tribune': 3,
	'the boston globe': 3,
	'the dallas morning news': 3,
	'san francisco chronicle': 3,
	'the philadelphia inquirer': 3,
	'the atlanta journal-constitution': 3,
	'detroit news': 3,
	'the miami herald': 3,
	'the seattle times': 3,
	'kc star': 3,
	'kansas city star': 3,
	'government technology': 3,
	'techcrunch': 3,

	'le monde': 3,
	'der spiegel': 3,
	'france 24': 3,
	'euronews': 3,
}
